name: bimental_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Para hacer llamadas HTTP
  font_awesome_flutter: ^10.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.18.0  # Usa la versi칩n m치s reciente disponible.
  path_provider: ^2.0.11
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2 # o la versi칩n m치s recient
  cloud_firestore: ^5.6.5
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
