// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cCdkkHOnRkb5bloXI1j5rG14a2-5lJw',
    appId: '1:381340908284:web:28d06242a7d8359c8ab579',
    messagingSenderId: '381340908284',
    projectId: 'bimental-eecd7',
    authDomain: 'bimental-eecd7.firebaseapp.com',
    storageBucket: 'bimental-eecd7.firebasestorage.app',
    measurementId: 'G-HDXLY1SKLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlC-fZPUbwRAg3yLNDAVle_IYzrhZ5s9A',
    appId: '1:381340908284:android:56ada9d6ea63b5098ab579',
    messagingSenderId: '381340908284',
    projectId: 'bimental-eecd7',
    storageBucket: 'bimental-eecd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAioYpX_l_4eGeWDZx18VVcP6GTKP53oqQ',
    appId: '1:381340908284:ios:6a49d6477f43efc88ab579',
    messagingSenderId: '381340908284',
    projectId: 'bimental-eecd7',
    storageBucket: 'bimental-eecd7.firebasestorage.app',
    iosBundleId: 'com.example.bimentalApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAioYpX_l_4eGeWDZx18VVcP6GTKP53oqQ',
    appId: '1:381340908284:ios:6a49d6477f43efc88ab579',
    messagingSenderId: '381340908284',
    projectId: 'bimental-eecd7',
    storageBucket: 'bimental-eecd7.firebasestorage.app',
    iosBundleId: 'com.example.bimentalApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cCdkkHOnRkb5bloXI1j5rG14a2-5lJw',
    appId: '1:381340908284:web:5c84e2f67f7bec9b8ab579',
    messagingSenderId: '381340908284',
    projectId: 'bimental-eecd7',
    authDomain: 'bimental-eecd7.firebaseapp.com',
    storageBucket: 'bimental-eecd7.firebasestorage.app',
    measurementId: 'G-G2GZTQHWBJ',
  );
}
