name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.configureondemand=false"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      # Ir al directorio del proyecto Flutter
      - name: Set working directory
        run: echo "Working directory set"
        working-directory: bimental_application_1

      # Limpieza antes del build (IMPORTANTE)
      - name: Flutter clean
        working-directory: bimental_application_1
        run: flutter clean

      - name: Flutter pub get
        working-directory: bimental_application_1
        run: flutter pub get

      - name: Build AAB Release
        working-directory: bimental_application_1
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bimental_application_1/build/app/outputs/bundle/release/app-release.aab
